version: '2'
services:
  jenkins-docker-server:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ~/docker-repository/ci_env/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/bin/docker.io
